create_node_pi_led
rogy-AquaLab/2024_cavolinia pull request #50
Opened 2024-07-21 03:16 UTC by 23-saho

#49 
Documentationと他のコードを参考に書いてみたのですがやっていることがあっているのかわからないです

pinのパラメータの話もよくわかっていないです…
新しくpin番号を書いたファイルを作ってそれを読み込む形にする感じですか

2024-07-21 10:55 UTC, H1rono requested changes

2024-07-21 10:55 UTC, H1rono commented on device/pi_led/pi_led/pi_led.py
> +        self.led_b = LED(22)
ピン番号は`"GPIOxx"`の形式で指定して欲しいです
ref: https://gpiozero.readthedocs.io/en/latest/recipes.html#pin-numbering
parameter使うやつは後でやります

2024-07-21 10:55 UTC, H1rono commented on device/pi_led/pi_led/pi_led.py
> +            'R is "%d",G is "%d",B is "%d"' % (self.led_R, self.led_G, self.led_B)
rgbが大文字になっちゃってる

```suggestion
            'R is "%d",G is "%d",B is "%d"' % (self.led_r, self.led_g, self.led_b)
```

2024-07-21 10:55 UTC, H1rono commented on device/pi_led/pi_led/pi_led.py
> +    def led_light(led, light):
`self`忘れてる
使わん場合でも必要です

```suggestion
    def led_light(self, led, light):
```

2024-07-21 10:55 UTC, H1rono commented on device/pi_led/test/test_copyright.py
言い忘れてたんですが`test`フォルダ以下のものは全部消しちゃって下さい、テストしないので

2024-07-21 10:55 UTC, H1rono commented on device/rpi-bno055
なんだこれ、何か変えた覚えありますか？

2024-07-22 04:08 UTC, 23-saho commented on device/rpi-bno055
覚えないです
mainブランチにも表示されていて、ワークスペースを入れ直したりなどしていたのですが消えませんでした
![Screenshot from 2024-07-22 13-07-38](https://github.com/user-attachments/assets/6c66a3bc-b286-44e9-bdeb-e4587fff175c)

2024-07-22 15:02 UTC, 23-saho commented
error直すためにインストール等のコマンド実行してもファイル自体は変更されないのでどうすればよいのかわからないです…

2024-07-23 05:56 UTC, H1rono commented
@23-saho 直してpushしたので、`2024_umiusi`フォルダで↓を実行してください

```bash
git pull
git switch raspi_led
git pull
git submodule update --init --remote
```

2024-07-23 13:21 UTC, H1rono commented
@23-saho Node起動時、つまり`__init__`内でparameterを読み込むようにしたいんだけど、やり方わかりますか

2024-07-23 14:53 UTC, 23-saho commented
資料読んでできると思います
やってみます

2024-07-24 08:31 UTC, H1rono commented
@23-saho 一回pullお願いします

2024-07-24 08:39 UTC, H1rono requested changes

2024-07-24 08:39 UTC, H1rono commented on device/pi_led/pi_led/pi_led.py
> +            'R is "%d",G is "%d",B is "%d"' % (self.led_r, self.led_g, self.led_b)
`gpiozero.Led`型はformatできないのでダメです

```suggestion
            f'R is "{int(light.red)}",G is "{int(light.green)}",B is "{int(light.blue)}"'
```

`int()`で包まなくてもいい

2024-07-24 10:04 UTC, H1rono commented on device/pi_led/setup.py
> +        "console_scripts": [],
ここ書いてください

参考:
https://github.com/rogy-AquaLab/2024_umiusi/blob/5302472868d4d2e8c8c00bf2d259458db47ea5b9/device/nucleo_communicate_py/setup.py#L28-L32
https://setuptools.pypa.io/en/latest/userguide/quickstart.html#entry-points-and-automatic-script-creation

2024-07-24 10:06 UTC, H1rono commented
parameterの使用箇所で参考になりそうなとこ:
https://github.com/rogy-AquaLab/2024_umiusi/blob/5302472868d4d2e8c8c00bf2d259458db47ea5b9/device/camera_reader/camera_reader/camera.py#L14-L19

2024-07-26 10:13 UTC, 23-saho commented
ymlファイル作ろうとしたのですがこの後わからないです
power_mapと似た感じですか

2024-07-26 15:34 UTC, H1rono reviewed
YAMLファイルの前にlaunchファイルが必要なので、まずはそっちをお願いします
参考: https://github.com/rogy-AquaLab/2024_umiusi/blob/5302472868d4d2e8c8c00bf2d259458db47ea5b9/device/pi_i2c/launch/imu_launch.py

それに伴って`launch`ディレクトリもインストールする必要があるので、setup.pyも↓と同じ内容を足してください

https://github.com/rogy-AquaLab/2024_umiusi/blob/5302472868d4d2e8c8c00bf2d259458db47ea5b9/device/pi_i2c/setup.py#L15-L18

2024-07-26 15:34 UTC, H1rono commented on device/pi_led/pi_led/pi_led.py
> +        param_b = self.declare_parameter("led_pin_b", "")
parameterのデフォルト値にはGPIOのピンを書いておいてください(parameter設定前に仮で置いたやつ)

2024-07-27 04:38 UTC, H1rono commented
https://docs.ros.org/en/iron/Tutorials/Intermediate/Launch/Using-ROS2-Launch-For-Large-Projects.html#loading-parameters-from-yaml-file とりあえずここに書いてある通りに色々を用意して欲しいんですが、具体的に何やるか書いておきますね

<details>

**parameterファイルを用意する**

`config/default_param.yml`を書く。記述例↓

https://github.com/rogy-AquaLab/2024_umiusi/blob/5302472868d4d2e8c8c00bf2d259458db47ea5b9/app/power_map/config/default_param.yml

```yaml
/**
  ros__parameters:
    led_pin_r: GPIO17
    led_pin_g: GPIO27
    led_pin_b: GPIO22
```

**configディレクトリをインストール対象にする**

https://github.com/rogy-AquaLab/2024_umiusi/blob/5302472868d4d2e8c8c00bf2d259458db47ea5b9/device/camera_reader/setup.py#L19-L22

**launchファイルからYAMLファイルを読み込む**

https://github.com/rogy-AquaLab/2024_umiusi/blob/5302472868d4d2e8c8c00bf2d259458db47ea5b9/device/camera_reader/launch/camera_reader_launch.py#L9-L13

https://github.com/rogy-AquaLab/2024_umiusi/blob/5302472868d4d2e8c8c00bf2d259458db47ea5b9/device/camera_reader/launch/camera_reader_launch.py#L20

</details>

2024-07-27 04:42 UTC, H1rono commented on device/pi_led/pi_led/pi_led.py
> +        param_b = self.declare_parameter("led_pin_b", "GPIO 22")
空白あるとまずい

```suggestion
        param_r = self.declare_parameter("led_pin_r", "GPIO17")
        param_g = self.declare_parameter("led_pin_g", "GPIO27")
        param_b = self.declare_parameter("led_pin_b", "GPIO22")
```

2024-07-27 15:39 UTC, 23-saho commented
ledを左右で別に立ち上げて、デフォルトは片方（今は右）のgpioになっているので、もう片方はそのgpioを書いたyamlファイル（setup.pyに含まない）をどこかにおいておいて"ros2 param load"で読み込む、
であってますか

2024-07-27 15:50 UTC, H1rono reviewed
:+1:
`left_param.yml`とかの名前でもう片方のピン設定も書いておいて欲しいです

2024-07-27 15:52 UTC, H1rono commented
> ledを左右で別に立ち上げて、デフォルトは片方（今は右）のgpioになっているので、もう片方はそのgpioを書いたyamlファイル（setup.pyに含まない）をどこかにおいておいて"ros2 param load"で読み込む、 であってますか

かなり近いんですが、parameterの値が見られるのはNode起動時だけなので`ros2 param load`だと意味がないんですよね...

launchファイルのargumentという仕組みがROS2にあるのでそれを使おうと思ってます、このPRではとりあえずここまででマージするつもりです

2024-07-27 18:09 UTC, H1rono approved these changes
LGTM

2024-07-27 18:09 UTC, merged