画像を圧縮して送受信
rogy-AquaLab/2024_cavolinia pull request #54
Opened 2024-07-31 15:51 UTC by 23-yoshikawa

2024-08-01 00:42 UTC, H1rono commented
@23-yoshikawa conflict解消したので一回pullしておいてください

2024-08-03 01:28 UTC, 23-yoshikawa commented
今日中にerror直します

2024-08-04 00:53 UTC, H1rono requested changes
他は大丈夫そうに見える
動作確認できてますか？

2024-08-04 00:53 UTC, H1rono commented on device/camera_reader/camera_reader/camera.py
> +        self.timer = self.create_timer(0.1, self.timer_callback)
タイマーの周期戻してください

2024-08-04 00:53 UTC, H1rono commented on device/camera_reader/camera_reader/camera.py
> +            msg.header=self._generate_header()
```suggestion
            msg.header = self._generate_header()
```

2024-08-04 08:46 UTC, 23-yoshikawa commented
PC上ではカメラ映像がうつりました

2024-08-04 14:38 UTC, H1rono approved these changes
LGTM

2024-08-04 14:50 UTC, 23-yoshikawa commented
> LGTM

コンフリクトの解消やアドバイスなどサポートしていただきありがとうございました！

2024-08-04 15:09 UTC, merged