Add log_level
rogy-AquaLab/2024_cavolinia pull request #62
Opened 2024-08-10 08:16 UTC by 23-yoshikawa

2024-08-10 08:26 UTC, H1rono requested changes
`log_level`周りはよくかけています
他のlaunchファイルにもお願いします :pray: :pray:

2024-08-10 08:26 UTC, H1rono commented on device/joystick/joystick/joystick.py
> +        self._joystick.init()
これ書いてもらったところ申し訳ないんですが、複数ゲームパッドへの対応は特に問題となっていないので戻してほしいです
"Add log_level"というPRのタイトルと変更内容が噛み合っていないというのもあります

2024-08-10 08:26 UTC, H1rono commented on device/joystick/launch/joystick_launch.py
> +    index_arg = DeclareLaunchArgument("index",default_value="-1")
`index`使いません :pray:

2024-08-10 15:40 UTC, 23-yoshikawa commented
今日中にエラー確認して修正します

2024-08-11 01:25 UTC, H1rono reviewed
かなり良さそう
一回`ruff format`と`ruff check --fix`をお願いします

2024-08-11 01:25 UTC, H1rono commented on device/joystick/launch/joystick_launch.py
> +        namespace="devide",
```suggestion
        namespace="device",
```

2024-08-11 01:25 UTC, H1rono commented on ul/launch/double_camera.py
> +        launch_arguments=[("index", "1"),("log_level", log_level)],
これだけで通るかどうか不安なので後で確認します

2024-08-11 09:03 UTC, H1rono commented on ul/launch/double_led.py
> +        description="Logging level for the nodes",
できればdescriptionついてない`log_level_arg`全部にこれ書いてほしいです :pray:

2024-08-17 14:03 UTC, H1rono requested changes
:pray:

2024-08-17 14:03 UTC, H1rono commented on ul/launch/double_camera.py
>      )
やっぱりこれだけだと通りません
`launch_configurations`を設定する必要があります、記述例↓

https://github.com/rogy-AquaLab/2024_umiusi/blob/fb19c0a3d37755fac958c8b7f78a11246edf3ac9/ul/launch/simple_joy_app_pc.py#L41

他の`IncludeLaunchDescription`を使っているところもこれをやる必要があるんですが、`GroupAction`の引数に設定する必要があるので気をつけてください

2024-08-24 11:26 UTC, 23-yoshikawa commented
遅くなってしまってすみません

2024-11-28 01:28 UTC, merged