make pacledt-compose'Node'
rogy-AquaLab/2024_cavolinia pull request #9
Opened 2024-06-02 07:47 UTC by Noir-swim

https://github.com/rogy-AquaLab/2024_cavolinia/issues/3

2024-06-03 01:36 UTC, H1rono requested changes
とりあえずこれだけ
あと今入ってる日本語のコメント全部消してください、とりあえず

2024-06-03 01:36 UTC, H1rono commented on packet/packet_composed/CMakeLists.txt
> + )
インデント怪しい

```suggestion
 add_executable(composed
   src/composed_main.cpp
   src/composed.cpp
 )
```

2024-06-03 01:36 UTC, H1rono commented on packet/packet_composed/CMakeLists.txt
> +   std_msgs     # ROS2が用意している標準的なmessage型の定義を含むライブラリ
依存関係違い

```suggestion
   packet_interfaces
```

2024-06-03 01:36 UTC, H1rono commented on packet/packet_composed/CMakeLists.txt
> + )
インデント修正

```suggestion
 install(TARGETS
     composed
   DESTINATION lib/${PROJECT_NAME}
 )
```

2024-06-03 01:36 UTC, H1rono commented on packet/packet_composed/CMakeLists.txt
> +
テストしないので消しちゃっていいです

```suggestion
```

2024-06-03 01:36 UTC, H1rono commented on packet/packet_composed/include/packet_composed/sensorspacket.hpp
> +};
ファイルの最後に空行1行入れて欲しいです

2024-06-03 01:36 UTC, H1rono commented on packet/packet_composed/src/composed.cpp
> +}
ここも空行1行

2024-06-03 01:36 UTC, H1rono commented on packet/packet_composed/src/composed_main.cpp
> +}
空行

2024-06-03 01:36 UTC, H1rono commented on packet/packet_composed/include/packet_composed/sensorspacket.hpp
[インクルードガード](https://cpp.aquariuscode.com/include_guard)入れて欲しいです

```cpp
#ifndef PACKET_COMPOSED_SENSORPACKET_HPP
#define PACKET_COMPOSED_SENSORPACKET_HPP

...

#endif // PACKET_COMPOSED_SENSORPACKET_HPP
```

2024-06-10 12:50 UTC, H1rono commented on packet/packet_composed/include/packet_composed/sensorspacket.hpp
> +};
入ってなさそう

2024-06-10 13:00 UTC, H1rono commented on packet/packet_composed/include/packet_composed/sensorspacket.hpp
> +#define PACKET_COMPOSED_SENSORPACKET_HPP
順序逆の方がいいです

```suggestion
#ifndef PACKET_COMPOSED_SENSORPACKET_HPP
#define PACKET_COMPOSED_SENSORPACKET_HPP

#include <memory>
#include "rclcpp/rclcpp.hpp"
#include "std_msgs/msg/string.hpp"
```

2024-06-10 13:00 UTC, H1rono commented on packet/packet_composed/include/packet_composed/sensorspacket.hpp
> +class composed : public rclcpp::Node {
型の名前は大文字始まりにしてください

余談ですが、ここでは以下の[命名規則](https://qiita.com/deerboy/items/f035b9044edf9a51aff7)を使用します。

- クラス・構造体など型: UpperCamelCase
- 変数・関数: snake_case
- マクロ: UPPER_SNAKE_CASE

2024-06-10 13:00 UTC, H1rono commented on packet/packet_composed/package.xml
> +  <license>TODO: License declaration</license>
```suggestion
  <license>MIT</license>
```

2024-06-10 13:00 UTC, H1rono commented on packet/packet_composed/package.xml
> +
ここ消しちゃってください、テストしないので

```suggestion
```

2024-06-10 13:01 UTC, H1rono commented on packet/packet_composed/include/packet_composed/sensorspacket.hpp
> +};
入ってないです

2024-06-10 13:42 UTC, H1rono requested changes

2024-06-10 13:42 UTC, H1rono commented on packet/packet_composed/src/composed.cpp
> +    _publisher = this->create_publisher<std_msgs::msg::String>("/sensorspacket", 10);
```suggestion
    _publisher = this->create_publisher<std_msgs::msg::String>("sensors_composed", 10);
```

2024-06-17 14:09 UTC, Noir-swim commented
slackでお騒がせしてすみません。
今、packet_interfacesのmsgファイルに対する出力関係のノード等をFigma(https://www.figma.com/board/auJaW4Ava0yzcklB8T6eJX/24jam?node-id=0-1&t=zgHRTrbp86YCIbpF-1)
見ながら作ったつもりのコードをpushしました。
しかし、ディレクトリの構造が違ったり、解釈違いで余計なことをしている気がします。
ご指摘いただきたいです。
また、トピック名は良い名前が思いつかずhppファイルの名前をそのまま書きました。改名を希望しております。
よろしくお願いいたしますm(_ _)m　m(_ _)m

2024-06-18 22:09 UTC, H1rono requested changes
**作成するnodeは一つだけでいいです**
欲しいのは"複数のtopicをsubscribeして一つのtopicにまとめるnode"なので, 以下のようなクラス定義が与えられます

```cpp
class Composed : public rclcpp::Node {
private:
    rclcpp::Publisher<packet_interfaces::msg::Composed>::SharedPtr composed_publisher;

    rclcpp::Subscription<packet_interfaces::msg::Depth>::SharedPtr depth_subscription;
    rclcpp::Subscription<sensor_msgs::msg::Imu>::SharedPtr         imu_subscription;
    rclcpp::Subscription<packet_interfaces::msg::Flex>::SharedPtr  flex1_subscription;
    rclcpp::Subscription<packet_interfaces::msg::Flex>::SharedPtr  flex2_subscription;
    // current, voltageのsubscriptionは略

    void depth_topic_callback(const packet_interfaces::msg::Depth& msg);
    void imu_topic_callback(const sensor_msgs::msg::Imu& msg);
    void flex1_topic_callback(const packet_interfaces::msg::Flex& msg);
    void flex2_topic_callback(const packet_interfaces::msg::Flex& msg);
    // current, voltageのcallbackは略

    // さらにいくつかのメソッド, プロパティが必要になる

public:
    Composed();
};
```

より具体的には, "subscribeしたtopicの内容を記憶し, それらを組み合わせたtopicを定期的にpublishする"といったnodeになると思います.

2024-06-23 10:48 UTC, Noir-swim commented
今、コメントを読んでコードを変更しているところです。

私がやる方向性として
複数のセンサーデータを受信し、それをまとめて別のメッセージとして発行するノードのヘッダーファイルを作る。
Composedクラスがセンサーデータ（Depth、IMU、Flexなど）を受信し、それらを1つのComposedメッセージとしてまとめてパブリッシュする。ということまで理解しております。←あってますでしょうか？

このことを理解してpacket_composed/src内にあるcompsed.cppとcomposed_main.cpp、CMakeLists.txt、package.xmlt,
include内のsensorspacket.hppに変更を加えてPR出そうとしています。

ということは、この前私がPRを出したときにdepthなどの複数のノードを作成したパッケージは削除して、一番最初に作成したcomposedのファイルだけ残せばよいのでしょうか？

ちなみにまだ、ファイルを一切消していません。。

よろしくお願いいたします。

2024-06-23 11:17 UTC, H1rono commented
> 複数のセンサーデータを受信し、それをまとめて別のメッセージとして発行するノードのヘッダーファイルを作る。
> Composedクラスがセンサーデータ（Depth、IMU、Flexなど）を受信し、それらを1つのComposedメッセージとしてまとめてパブリッシュする。ということまで理解しております。

あってる！Flexは2つあるので注意してください。
あと、センサーデータはそれぞれ別のタイミングで送られてくるので、それらをまとめてpublishするためにタイマーが必要になるかもしれません(何か別の方法でpublishの処理を書いてもいいです)。

> ということは、この前私がPRを出したときにdepthなどの複数のノードを作成したパッケージは削除して、一番最初に作成したcomposedのファイルだけ残せばよいのでしょうか？

あってる！！他のやつはバッサリ捨てちゃってください :fire:

2024-06-23 11:21 UTC, Noir-swim commented
ありがとうございます！！！
了解です。考えてみます！

2024-06-25 15:27 UTC, Noir-swim commented
https://github.com/rogy-AquaLab/2024_cavolinia/issues/3
お疲れ様です。PR出してみました。

色々と調べて、Composedクラスがセンサーデータ（Depth、IMU、Flexなど）を受信し、それらを1つのComposedメッセージとしてまとめてパブリッシュする。
センサーデータをまとめてpublishするためにタイマーを作る。
つもりのコードを書き足してみました。

[自分がした大まかな手順]
①不要なファイルを削除した。
以下、[composed.cpp、sensorspacket.hpp,CMakeLists.txt,package.xmlt]を変更させた。
②複数のサブスクリプションを通じて、（Depth、IMU、Flex1、Flex2、Current、Voltage）を受信させた。
③各センサーデータに対応するmsgを受信し、それをComposed_msgに追加してパブリッシュした。
④コンストラクタの初期化してメンバ変数を初期化した。
⑤コールバックごとに新しいComposedメッセージを作成するのではなく、1つのメッセージを再利用して更新した。

このノードでやりたいことはわかるのですが、、
ところどころ文法などが滅茶苦茶になっていると思います。。
雑なコードですみません(._.)
添削お願いします。。

2024-06-26 06:44 UTC, H1rono requested changes
やりたいのは「複数topicを受信して、 **一つの** topicにまとめて **同時に** publishする」ということです。今のコードだと「一つのtopicにまとめる」ところはできてますが、「同時にpublishする」というのができていません。これを実現するためには、以下のようにする必要があります。

- subscriptionで受信したtopicを一度保存する
- タイマー機能で、保存されているtopicを一つにまとめてpublishする

この「一度保存する」というのをどう実現するかが少し難しいところですが、考えて見てください。(しばらく考えてわかんなかったら教えてください)

2024-06-26 06:44 UTC, H1rono commented on packet/packet_composed/.vscode/c_cpp_properties.json
必要ないので消してください

2024-06-26 06:44 UTC, H1rono commented on packet/packet_composed/.vscode/settings.json
必要ないです

2024-06-26 06:44 UTC, H1rono commented on packet/packet_composed/include/packet_composed/sensorspacket.hpp
> +    rclcpp::Subscription<packet_interfaces::msg::voltage>::SharedPtr  voltage_subscription;
```suggestion
    rclcpp::Subscription<packet_interfaces::msg::Current>::SharedPtr  current_subscription;
    rclcpp::Subscription<packet_interfaces::msg::Coltage>::SharedPtr  voltage_subscription;
```

2024-06-26 06:44 UTC, H1rono commented on packet/packet_composed/include/packet_composed/sensorspacket.hpp
> +    rclcpp::Publisher<packet_interfaces::msg::Composed>::SharedPtr composed_publisher;
stringの方はもう必要ないです
```suggestion
    rclcpp::Publisher<packet_interfaces::msg::Composed>::SharedPtr composed_publisher;
```

2024-06-26 06:44 UTC, H1rono commented on packet/packet_composed/package.xml
> +  <exec_depend>packet_interfaces</exec_depend>
ここ冗長なのでいらないです

```suggestion
```

2024-06-26 06:44 UTC, H1rono commented on packet/packet_composed/src/composed.cpp
> +    composed_publisher = this->create_publisher<packet_interfaces::msg::Composed>("composed_topic", 10);
stringのpublishはしません & topic名はFigmaのやつ(から`/packet/`のプレフィックスを取り除いたもの)と合わせるようにお願いします

```suggestion
    composed_publisher = this->create_publisher<packet_interfaces::msg::Composed>("sensors_composed", 10);
```

2024-06-26 06:44 UTC, H1rono commented on packet/packet_composed/src/composed.cpp
> +        "voltage_topic", 10, std::bind(&Composed::voltage_topic_callback, this, std::placeholders::_1));
ここのtopic名も書き換えてください

2024-06-26 06:44 UTC, H1rono commented on packet/packet_composed/src/composed.cpp
> +    RCLCPP_INFO(this->get_logger(), "Received Depth message");
ログのレベルはデバッグでお願いします(他のcallback部分も同様)

```suggestion
    RCLCPP_DEBUG(this->get_logger(), "Received Depth message");
```

2024-06-26 06:45 UTC, H1rono commented on packet/packet_composed/.vscode/c_cpp_properties.json
commitしないでねという意味であって、ローカルリポジトリで存在してても問題ないです

2024-06-28 05:29 UTC, Noir-swim commented on packet/packet_composed/src/composed.cpp
> +    composed_publisher = this->create_publisher<packet_interfaces::msg::Composed>("composed_topic", 10);
![image](https://github.com/rogy-AquaLab/2024_cavolinia/assets/145688154/c438b5cc-8bfa-4aff-b44e-5003be849fd6)
voltageの部分なら、`packets/sensors/voltage`で`voltage`と、topic名を書いてみたのですが、あってますか？

2024-06-28 07:01 UTC, Noir-swim commented
一旦、上記のコメント読んで直したファイルをcommit→PR出しました。
👀のマークがついているところは直しが怪しいところです。
間違っていたらご指摘お願いします。

「同時にpublishする」という部分については考え中です。
subscriptionで受信したtopicを一度保存するタイマー機能で、保存されているtopicを一つにまとめてpublishする。方法について今考えています。
日曜日まで考えてみます。m(_ _)m

個人的に浮かんだ考え方はcomposed.cppのcomposedのループを利用すればいいと思っています。
```
void Composed::_loop() {
    std::stringstream ss;
    ss << "Hello, world! " << _count;
    std_msgs::msg::String msg{};
    msg.data = ss.str();
    RCLCPP_INFO(this->get_logger(), "say %s", ss.str().c_str());
    _publisher->publish(msg);
    _count++;
}
```
この部分にif文を追加して、同時に受け取ったときpublishするというif文を作る。
「一度保存させる」ためにはsensorspacket.hppのprivate メンバにそれぞれのsubscliptionで受信したtopicが適切に入れるような関数を個々につくって保存する。
この２つの方向性で考えています。。

2024-06-28 08:03 UTC, H1rono commented on packet/packet_composed/src/composed.cpp
> +        "voltage_topic", 10, std::bind(&Composed::voltage_topic_callback, this, std::placeholders::_1));
<img width="679" alt="スクリーンショット 2024-06-28 17 02 07" src="https://github.com/rogy-AquaLab/2024_cavolinia/assets/54711422/1f27ccb4-04a9-4b9d-8967-9f2be18d4fe9">

ここの`/packet/`プレフィックスを取り除いたものなので、`sensors_composed`, `sensors/imu`, `sensors/flex/1`, ...って感じです

2024-06-28 08:08 UTC, H1rono commented
> 個人的に浮かんだ考え方はcomposed.cppのcomposedのループを利用すればいいと思っています

あってる。`_loop`関数内で`composed_publisher->publish`を呼ぶことになるはずです

> この部分にif文を追加して、同時に受け取ったときpublishするというif文を作る。

subscriptionのcallbackとtimerのcallbackは**非同期に**呼ばれるので、「同時に受け取った時」を判定するのはとても難しそうです。

> 「一度保存させる」ためにはsensorspacket.hppのprivate メンバにそれぞれのsubscliptionで受信したtopicが適切に入れるような関数を個々につくって保存する。

良さそうだけど、関数ではなく状態、ないしメンバ変数かな

2024-06-30 08:08 UTC, Noir-swim commented on packet/packet_composed/src/composed.cpp
> +    composed_publisher = this->create_publisher<packet_interfaces::msg::Composed>("composed_topic", 10);
この部分変えてなかったです。topic名変えました。

2024-06-30 08:08 UTC, Noir-swim commented on packet/packet_composed/src/composed.cpp
> +        "voltage_topic", 10, std::bind(&Composed::voltage_topic_callback, this, std::placeholders::_1));
ありがとうございます。勘違いしていたようです。トピック名直してみました。

2024-06-30 08:20 UTC, Noir-swim commented
今の状況として、、

composed.cppのcomposedのループを利用してみた。
_loop関数内で`composed_publisher->publish`を呼んでみました。
「一度保存させる」ためにsensorspacket.hppのprivate メンバにそれぞれのsubscliptionで受信したtopicが適切に入れるようなメンバ変数をいれてみた。

```_depth_received(), _imu_received(), _flex1_received(), _flex2_received(),_current_received(), _voltage_received()　など
```
![image](https://github.com/rogy-AquaLab/2024_cavolinia/assets/145688154/1421bf14-8cf4-480b-9423-39ba7a4c52c0)

subscriptionのcallbackとtimerのcallbackは非同期に呼ばれるので、「同時に受け取った時」を判定できないので、どうしたら、タイマー機能で、保存されているtopicを一つにまとめてpublishすることができるのか悩んでいます。。

2024-06-30 09:11 UTC, H1rono requested changes
かなり良くなってきました :+1:
日本語コメントとコメントアウトした部分は全部いらないので消しちゃってください

2024-06-30 09:11 UTC, H1rono commented on packet/packet_composed/src/composed.cpp
> +    // _count++;
いらないので消してください
`_count`変数もいらないので消しちゃって

2024-06-30 09:11 UTC, H1rono commented on packet/packet_composed/src/composed.cpp
> +        "sensors/voltage", 10, std::bind(&Composed::, this, std::placeholders::_1));
```suggestion
        "sensors/voltage", 10, std::bind(&Composed::voltage_topic_callback, this, std::placeholders::_1));
```

2024-06-30 09:11 UTC, H1rono commented on packet/packet_composed/src/composed.cpp
> +    _timer = this->create_wall_timer(500ms, loop);
もうちょい周波数高くていいかも

```suggestion
    _timer = this->create_wall_timer(10ms, loop);
```

2024-06-30 09:11 UTC, H1rono commented on packet/packet_composed/src/composed.cpp
> +    if (_depth_received && _imu_received && _flex1_received && _flex2_received && _current_received && _voltage_received)
この実装でも "同時にpublishする" というのは達成できてますね. :tada:
ただ, これだとpublishの周波数が低いセンサーに他のセンサーが律速されることになってしまいます.

例えば, センサーのデータがそれぞれ以下の周波数でpublishされていたとします.

- 深さセンサーは50Hz(20msに一回)
- その他のセンサーは60Hz(約17msに一回)

この場合, `depth_topic_callback`が50Hz, その他のcallbackが60Hzで呼ばれることになります. timerの周波数が100Hzとすると, `_loop`関数が10msおきに呼ばれ, フラグとなる`*_received`のメンバ変数はそれぞれ以下の周波数で`true`になります.

- `_depth_received`: 50Hz
- その他: 60Hz

結果として, この場合は`_depth_received && _imu_received && ...`の条件式が50Hzの周波数で`true`になり, `composed_publisher->publish`が50Hzの周波数で呼ばれることになります.

---

という状況が困るので, `_loop`内では "最後に受信したデータをまとめて一度にpublishする" ようにしたいです. 平たくいうと, `_depth_received = false; _imu_received = false; ...`の部分はいらないです

2024-07-02 10:31 UTC, Noir-swim commented
遅くなってしまいすみません。
コメントありがとうございます！！
修正しました。
よろしくお願いいたします。

2024-07-02 22:02 UTC, H1rono requested changes
これだけかなー

2024-07-02 22:02 UTC, H1rono commented on packet/packet_composed/package.xml
> +  <depend>packet_interfaces</depend>
```suggestion
  <depend>packet_interfaces</depend>
```

2024-07-02 22:02 UTC, H1rono commented on packet/packet_composed/include/packet_composed/sensorspacket.hpp
> +    size_t _count;
`_count`消えてないです

```suggestion
```

2024-07-04 05:12 UTC, Noir-swim commented
修正しました。お願いします。
sensors_composedたちはだいたいできてきたのですが、
残りの箇所として緊急停止命令、BLDCとサーボの出力のまとめ、カメラ画像を送りつける、
ゲームパッドの値たちの出力が残っていると思ってます。
進捗的に優先順序はどこから手を付ければ良い感じですか？
![Screenshot from 2024-07-04 14-07-46](https://github.com/rogy-AquaLab/2024_cavolinia/assets/145688154/cafe646b-8c2b-413f-810e-3d638db6d8a2)

2024-07-10 05:34 UTC, H1rono approved these changes
LGTM

2024-07-10 05:35 UTC, merged